import crypto from 'node:crypto';
import { Request, Response } from 'express';
import { citiFxService } from '../services/citiFx.js';
import { npciRailService } from '../services/npciRail.js';
import {
  CorridorEvent,
  EscrowState,
  HTLCEscrow,
  RemittanceRequest,
  SystemStatus,
} from '../types.js';

// In-Memory Enterprise Ledger (Drunix / Hyperledger Fabric World State)
class DrunixLedger {
  private escrows: Map<string, HTLCEscrow> = new Map();
  private blockHeight: number = 849204;
  private eventLog: CorridorEvent[] = [];
  private eventListeners: ((event: CorridorEvent) => void)[] = [];

  constructor() {
    this.seedDemoData();
  }

  public onEvent(callback: (event: CorridorEvent) => void) {
    this.eventListeners.push(callback);
  }

  public emitEvent(event: CorridorEvent) {
    this.eventLog.unshift(event);
    if (this.eventLog.length > 100) {
      this.eventLog.pop();
    }
    for (const listener of this.eventListeners) {
      listener(event);
    }
  }

  public getEvents(): CorridorEvent[] {
    return this.eventLog;
  }

  public getEscrows(): HTLCEscrow[] {
    return Array.from(this.escrows.values()).sort((a, b) => b.createdAt - a.createdAt);
  }

  public getEscrow(id: string): HTLCEscrow | undefined {
    return this.escrows.get(id);
  }

  public createEscrow(escrow: HTLCEscrow): HTLCEscrow {
    this.blockHeight += 1;
    this.escrows.set(escrow.escrowId, escrow);
    return escrow;
  }

  public updateEscrow(escrow: HTLCEscrow): HTLCEscrow {
    this.blockHeight += 1;
    this.escrows.set(escrow.escrowId, escrow);
    return escrow;
  }

  public getBlockHeight(): number {
    return this.blockHeight;
  }

  private seedDemoData() {
    // Seed one completed historical transaction for demonstration
    const seedPreimage = 'a3f8902c4819d45e7810bcf28192019482910482910294829104829104829104';
    const seedHash = crypto.createHash('sha256').update(Buffer.from(seedPreimage, 'hex')).digest('hex');
    const now = Math.floor(Date.now() / 1000) - 300;

    const seedEscrow: HTLCEscrow = {
      escrowId: 'ESCROW-PVP-9021',
      senderId: 'CITI_NY_TREASURY_CORP_01',
      receiverVpa: 'priya.sharma@okhdfcbank',
      amount: 1500,
      tokenSymbol: 'USD',
      hashLock: seedHash,
      timeLock: now + 60,
      state: 'SETTLED',
      secretPreimage: seedPreimage,
      createdAt: now,
      settledAt: now + 12,
      disbursedTo: 'priya.sharma@okhdfcbank',
      fxRate: 86.40,
      inrAmount: 129276.0,
      feeUsd: 3.75,
      savingsUsd: 108.75,
      railType: 'UPI',
      utrNumber: 'NPCI418290129384',
      blockNumber: this.blockHeight,
      ledgerTxHash: '0x71e982d6b389104829104cde78a2301982bca819203984029182390192830192',
    };
    this.escrows.set(seedEscrow.escrowId, seedEscrow);
  }
}

export const drunixLedger = new DrunixLedger();

// Controller handlers
export const remitController = {
  /**
   * GET /api/quote
   * Computes instant wholesale FX quote and fee savings
   */
  getQuote: (req: Request, res: Response) => {
    try {
      const amount = Number.parseFloat(req.query.amount as string) || 1000.0;
      const timeLockSeconds = Number.parseInt(req.query.timeLockSeconds as string, 10) || 60;

      if (amount <= 0) {
        return res.status(400).json({ error: 'Amount must be greater than zero' });
      }

      const quote = citiFxService.generateQuote(amount, timeLockSeconds);

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'QUOTE_REQUESTED',
        timestamp: Date.now(),
        stage: 1,
        title: 'Wholesale FX Quote Generated',
        details: `Citi NY quoted USD ${amount.toFixed(2)} @ ₹${quote.fxRate} (Fee: 0.25% vs legacy 4.5% + $45)`,
        status: 'pending',
        data: quote,
      });

      return res.json(quote);
    } catch (err: any) {
      return res.status(500).json({ error: err.message });
    }
  },

  /**
   * POST /api/initiate
   * Stage 1 & 2: Locks USD funds on HTLC contract with SHA-256 hash generated by NPCI rail
   */
  initiateRemittance: (req: Request, res: Response) => {
    try {
      const {
        usdAmount = 1000,
        receiverVpa = 'priya.sharma@okhdfcbank',
        senderId = 'CITI_NY_TREASURY_CORP_01',
        timeLockSeconds = 60,
        simulateFailure = false,
      }: RemittanceRequest = req.body;

      if (usdAmount <= 0) {
        return res.status(400).json({ error: 'Transfer amount must be positive' });
      }

      // Check and resolve beneficiary VPA
      const beneficiary = npciRailService.resolveVPA(receiverVpa);
      const quote = citiFxService.generateQuote(usdAmount, timeLockSeconds);

      // Check Citi USD liquidity
      const liquidityReserved = citiFxService.reserveLiquidity(usdAmount);
      if (!liquidityReserved) {
        return res.status(400).json({
          error: 'Insufficient Citi Treasury liquidity available for this transaction size',
        });
      }

      const escrowId = `ESCROW-PVP-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;

      // 1. NPCI rail generates cryptographic secret Preimage R and HashLock H = SHA256(R)
      const bundle = npciRailService.generatePreimageBundle(escrowId);

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'PREIMAGE_GENERATED',
        timestamp: Date.now(),
        escrowId,
        stage: 1,
        title: 'Cryptographic Preimage & HashLock Generated',
        details: `NPCI Enclave generated 256-bit secret R. Published HashLock H = ${bundle.hashLock.slice(0, 16)}...`,
        status: 'success',
        data: {
          hashLock: bundle.hashLock,
          preimageMasked: '•••••••••••••••••••••••••••••••• [LOCKED IN NPCI HSM ENCLAVE]',
          receiverVpa: beneficiary.vpa,
        },
      });

      const now = Math.floor(Date.now() / 1000);
      const timeLock = now + timeLockSeconds;
      const ledgerTxHash = `0x${crypto.randomBytes(32).toString('hex')}`;

      // 2. Lock USD in HTLC smart contract on Drunix ledger
      const escrow: HTLCEscrow = {
        escrowId,
        senderId,
        receiverVpa: beneficiary.vpa,
        amount: usdAmount,
        tokenSymbol: 'USD',
        hashLock: bundle.hashLock,
        timeLock,
        state: 'LOCKED',
        secretPreimage: undefined,
        createdAt: now,
        fxRate: quote.fxRate,
        inrAmount: quote.netInrRecipient,
        feeUsd: quote.citiFeeUsd,
        savingsUsd: quote.savingsUsd,
        railType: beneficiary.railType,
        blockNumber: drunixLedger.getBlockHeight() + 1,
        ledgerTxHash,
      };

      drunixLedger.createEscrow(escrow);

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'ESCROW_LOCKED',
        timestamp: Date.now(),
        escrowId,
        stage: 2,
        title: 'USD Liquidity Locked on Drunix Chaincode',
        details: `USD ${usdAmount.toLocaleString()} escrowed on ledger. Block #${escrow.blockNumber}. Timelock T = ${timeLockSeconds}s`,
        status: 'success',
        data: {
          escrowId,
          hashLock: bundle.hashLock,
          timeLock,
          blockNumber: escrow.blockNumber,
          ledgerTxHash,
        },
      });

      return res.json({
        success: true,
        escrow,
        quote,
        beneficiary,
        simulateFailure,
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message });
    }
  },

  /**
   * POST /api/settle
   * Stage 3 & 4: Simulates NPCI domestic rail credit and reveals preimage R to achieve atomic settlement
   */
  settleRemittance: (req: Request, res: Response) => {
    try {
      const { escrowId, simulateFailure = false } = req.body;

      if (!escrowId) {
        return res.status(400).json({ error: 'escrowId is required' });
      }

      const escrow = drunixLedger.getEscrow(escrowId);
      if (!escrow) {
        return res.status(404).json({ error: 'Escrow not found on ledger' });
      }

      if (escrow.state !== 'LOCKED') {
        return res.status(400).json({ error: `Cannot settle: escrow is already ${escrow.state}` });
      }

      const now = Math.floor(Date.now() / 1000);

      // Timelock expiry check
      if (now >= escrow.timeLock) {
        drunixLedger.emitEvent({
          id: crypto.randomUUID(),
          type: 'TIMELOCK_EXPIRED',
          timestamp: Date.now(),
          escrowId,
          stage: 3,
          title: 'Timelock Expired Before Claim',
          details: `Current time ${now} >= Timelock ${escrow.timeLock}. Settlement window closed. Eligible for atomic refund.`,
          status: 'warning',
        });
        return res.status(400).json({
          error: 'Timelock has expired. Settle cannot be completed. Trigger refund to reclaim funds.',
        });
      }

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'NPCI_ROUTING_STARTED',
        timestamp: Date.now(),
        escrowId,
        stage: 3,
        title: `Dispatching to Domestic Rail (${escrow.railType})`,
        details: `Verifying beneficiary ${escrow.receiverVpa} and executing domestic clearing leg...`,
        status: 'pending',
      });

      // 3. Process domestic rail credit (or simulate network drop)
      const creditResult = npciRailService.processDomesticCredit({
        hashLock: escrow.hashLock,
        vpa: escrow.receiverVpa,
        inrAmount: escrow.inrAmount,
        simulateFailure: Boolean(simulateFailure),
      });

      // Failure branch: Network drop / rail outage
      if (!creditResult.success || !creditResult.preimage) {
        drunixLedger.emitEvent({
          id: crypto.randomUUID(),
          type: 'NPCI_CREDIT_FAILED',
          timestamp: Date.now(),
          escrowId,
          stage: 3,
          title: 'Domestic Rail Outage / Network Drop',
          details: creditResult.error || 'Rail error: Secret preimage R WITHHELD by NPCI Enclave.',
          status: 'failed',
          data: { simulateFailure: true },
        });

        return res.status(502).json({
          success: false,
          error: creditResult.error,
          escrowState: escrow.state,
          timelockRemainingSeconds: Math.max(0, escrow.timeLock - now),
        });
      }

      // 4. Success Branch: Secret Preimage R revealed & verified deterministically on-chain
      const preimage = creditResult.preimage;

      // Deterministic SHA-256 validation (identically matching Go chaincode computeSHA256Hex)
      const computedHash = crypto
        .createHash('sha256')
        .update(Buffer.from(preimage, 'hex'))
        .digest('hex');

      if (computedHash.toLowerCase() !== escrow.hashLock.toLowerCase()) {
        return res.status(500).json({
          error: 'Cryptographic proof failure: SHA-256(preimage) does not match escrow HashLock',
        });
      }

      // Update escrow state on Drunix ledger to SETTLED
      escrow.state = 'SETTLED';
      escrow.secretPreimage = preimage;
      escrow.settledAt = now;
      escrow.disbursedTo = escrow.receiverVpa;
      escrow.utrNumber = creditResult.utrNumber;
      escrow.cbdcTxHash = creditResult.cbdcTxHash;

      drunixLedger.updateEscrow(escrow);
      citiFxService.commitSettlement(escrow.amount);

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'SECRET_REVEALED',
        timestamp: Date.now(),
        escrowId,
        stage: 4,
        title: 'Secret Preimage R Published On-Chain',
        details: `Preimage R: ${preimage.slice(0, 16)}... submitted. SHA-256 verification passed on chaincode!`,
        status: 'success',
        data: {
          preimage,
          hashLock: escrow.hashLock,
          verified: true,
        },
      });

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'ATOMIC_SETTLED',
        timestamp: Date.now(),
        escrowId,
        stage: 4,
        title: 'PvP Atomic Settlement Finalized',
        details: `USD ${escrow.amount.toLocaleString()} disbursed to Citi Domestic Clearing. ₹${escrow.inrAmount.toLocaleString()} credited to ${creditResult.beneficiaryName} (${escrow.utrNumber || escrow.cbdcTxHash})`,
        status: 'success',
        data: {
          escrow,
          newBeneficiaryBalance: creditResult.newBalance,
        },
      });

      return res.json({
        success: true,
        escrow,
        preimage,
        utrNumber: creditResult.utrNumber,
        cbdcTxHash: creditResult.cbdcTxHash,
        beneficiaryBalance: creditResult.newBalance,
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message });
    }
  },

  /**
   * POST /api/refund
   * Triggers atomic refund if timelock has elapsed and escrow is still LOCKED
   */
  refundRemittance: (req: Request, res: Response) => {
    try {
      const { escrowId, forceTimeSkip = false } = req.body;

      if (!escrowId) {
        return res.status(400).json({ error: 'escrowId is required' });
      }

      const escrow = drunixLedger.getEscrow(escrowId);
      if (!escrow) {
        return res.status(404).json({ error: 'Escrow not found' });
      }

      if (escrow.state !== 'LOCKED') {
        return res.status(400).json({ error: `Cannot refund: escrow state is already ${escrow.state}` });
      }

      const now = Math.floor(Date.now() / 1000);

      // Check timelock
      if (now < escrow.timeLock && !forceTimeSkip) {
        const remaining = escrow.timeLock - now;
        return res.status(400).json({
          error: `Timelock has not expired yet. ${remaining} seconds remaining before refund becomes executable.`,
          timelockRemainingSeconds: remaining,
        });
      }

      // Update state to REFUNDED
      escrow.state = 'REFUNDED';
      escrow.refundedAt = now;
      escrow.disbursedTo = escrow.senderId;

      drunixLedger.updateEscrow(escrow);
      citiFxService.releaseRefund(escrow.amount);

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'ESCROW_REFUNDED',
        timestamp: Date.now(),
        escrowId,
        stage: 4,
        title: 'Timelock Atomic Refund Executed',
        details: `Timelock elapsed without claim. USD ${escrow.amount.toLocaleString()} restored to Citi Treasury. Zero principal loss!`,
        status: 'success',
        data: {
          escrow,
          refundedTo: escrow.senderId,
        },
      });

      return res.json({
        success: true,
        escrow,
        message: 'Funds successfully refunded to sender treasury account.',
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message });
    }
  },

  /**
   * POST /api/fast-forward
   * Fast-forwards the timelock of an escrow to the past for instant demo testing
   */
  fastForwardTimelock: (req: Request, res: Response) => {
    try {
      const { escrowId } = req.body;
      const escrow = drunixLedger.getEscrow(escrowId);
      if (!escrow) {
        return res.status(404).json({ error: 'Escrow not found' });
      }

      const now = Math.floor(Date.now() / 1000);
      escrow.timeLock = now - 5; // Set to 5 seconds ago
      drunixLedger.updateEscrow(escrow);

      drunixLedger.emitEvent({
        id: crypto.randomUUID(),
        type: 'TIMELOCK_EXPIRED',
        timestamp: Date.now(),
        escrowId,
        stage: 3,
        title: 'Timelock Fast-Forwarded (Test Mode)',
        details: `Virtual ledger clock simulated timelock expiry (T = ${escrow.timeLock} < now = ${now})`,
        status: 'warning',
      });

      return res.json({
        success: true,
        escrow,
        message: 'Timelock has expired. Refund can now be executed.',
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message });
    }
  },

  /**
   * GET /api/escrows
   */
  listEscrows: (_req: Request, res: Response) => {
    return res.json({
      count: drunixLedger.getEscrows().length,
      escrows: drunixLedger.getEscrows(),
    });
  },

  /**
   * GET /api/escrows/:id
   */
  getEscrowById: (req: Request, res: Response) => {
    const escrow = drunixLedger.getEscrow(req.params.id);
    if (!escrow) {
      return res.status(404).json({ error: 'Escrow not found' });
    }
    return res.json(escrow);
  },

  /**
   * GET /api/beneficiaries
   */
  listBeneficiaries: (_req: Request, res: Response) => {
    return res.json(npciRailService.getAllBeneficiaries());
  },

  /**
   * GET /api/events
   */
  getRecentEvents: (_req: Request, res: Response) => {
    return res.json(drunixLedger.getEvents());
  },

  /**
   * GET /api/system-status
   */
  getSystemStatus: (_req: Request, res: Response) => {
    const citi = citiFxService.getTreasuryStatus();
    const npci = npciRailService.getRailStatus();

    const status: SystemStatus = {
      drunixLedger: {
        status: 'ONLINE',
        activeNodes: [
          'drunix-peer0.citi.newyork:7051',
          'drunix-peer0.npci.mumbai:7051',
          'drunix-orderer0.consortium:7050',
        ],
        currentBlockHeight: drunixLedger.getBlockHeight(),
        chaincodeVersion: 'nexus-pvp-htlc:v2.6',
        consensus: 'Raft / PBFT Enterprise BFT',
      },
      citiTreasury: {
        nodeId: citi.nodeId,
        location: citi.location,
        availableUsdLiquidity: citi.availableUsdLiquidity,
        lockedInEscrowUsd: citi.lockedInEscrowUsd,
        settledVolumeUsd: citi.settledVolumeUsd,
      },
      npciGateway: {
        nodeId: npci.nodeId,
        location: npci.location,
        railsConnected: npci.railsConnected,
        domesticSwitchStatus: npci.domesticSwitchStatus,
        availableInrLiquidity: npci.availableInrLiquidity,
        settledVolumeInr: npci.settledVolumeInr,
      },
    };

    return res.json(status);
  },
};
